// Fake database data for TV prop only. No live data.
// All addresses/notes are fictional and generated for screen use.

const SURNAME_POOL = [
  "AHERN","ALLEN","ARMSTRONG",
  "BARRY","BARTON","BEGLEY","BENNETT","BLAKE","BOLAND","BOURKE","BOYLE","BRADLEY","BRADY","BRENNAN","BROGAN","BROWNE","BYRNE","BURKE","BURNS",
  "CALLAGHAN","CAMPBELL","CAREY","CARNEY","CARROLL","CASEY","CLANCY","CLARKE","CLEARY","CLIFFORD","COFFEY","COGAN","COLLINS","CONNOLLY","CONNOR","CONROY","CORCORAN","CORRIGAN","COSTELLO","COUGHLAN","COYLE","CRONIN","CULLEN","CUNNINGHAM","CURTIN",
  "DALY","DELANEY","DEVLIN","DILLON","DOHERTY","DONNELLY","DOOLAN","DOYLE","DOWLING","DUGGAN","DUFFY","DUNNE",
  "EARLEY","EGAN","ENNIS",
  "FAHY","FANNING","FARRELL","FEELY","FINN","FINNEGAN","FITZGERALD","FITZPATRICK","FLAHERTY","FLANAGAN","FLYNN","FOLEY","FORDE",
  "GALLAGHER","GANNON","GARVEY","GIBBONS","GILLESPIE","GLYNN","GORMAN","GRAHAM","GRIFFIN","GUERIN",
  "HANLEY","HANNON","HARTE","HARTY","HAYES","HEALY","HEHIR","HENNESSY","HICKEY","HIGGINS","HOGAN","HOLMES","HOURIHANE","HOWARD","HUGHES",
  "IRWIN",
  "JOYCE","JORDAN",
  "KEANE","KEARNEY","KEATING","KELLEHER","KELLY","KENNEDY","KENNY","KERR","KIERAN","KIRBY","KIRWAN",
  "LANE","LARKIN","LEAHY","LEONARD","LOUGHRAN","LYNCH","LYONS",
  "MAHER","MALONE","MANNING","MARTIN","MAY","MCBRIDE","MCCABE","MCCANN","MCCARTHY","MCCORMACK","MCDERMOTT","MCDONAGH","MCDONNELL","MCGINLEY","MCGOUGH","MCGRATH","MCGUIRE","MCLOUGHLIN","MCMAHON","MCNAMARA","MEEHAN","MOLLOY","MONAGHAN","MOORE","MORAN","MORIARTY","MORRISSEY","MULCAHY","MULLEN","MURPHY","MURRAY",
  "NASH","NEVILLE","NOLAN","NOONAN",
  "O'BRIEN","O'CALLAGHAN","O'CONNELL","O'CONNOR","O'DEA","O'DONNELL","O'DWYER","O'HALLORAN","O'HARA","O'KEEFFE","O'LEARY","O'LOUGHLIN","O'MAHONY","O'MALLEY","O'MEARA","O'NEILL","O'REILLY","O'ROURKE","O'SHEA","O'SULLIVAN","O'TOOLE",
  "POWER","PRYOR","PURCELL",
  "QUIGLEY","QUINN","QUIRKE",
  "RAFFERTY","REID","REILLY","REYNOLDS","ROCHE","ROONEY","ROWE","RYAN",
  "SCANLON","SHANAHAN","SHEAHAN","SHEEHAN","SHERIDAN","SLATTERY","SMITH","SMYTH","STACK","STAUNTON","SULLIVAN","SWEENEY",
  "TIERNEY","TOBIN","TRACEY","TREACY","TROY",
  "UNDERWOOD",
  "VAUGHAN",
  "WADE","WALSH","WARD","WATERS","WHITE","WHELAN","WOODS",
  "XAVIER",
  "YOUNG",
  "ZAMMIT"
];

const FORENAME_POOL = [
  "ADAM","AIDAN","ALAN","ANDREW","ANTHONY","BARRY","BEN","BERNARD","BILLY","BRIAN","CALLUM","CARL","CATHAL","CHARLES","CHRIS","CIAN","CIARAN","COLIN","COLM","CONOR","DAMIEN","DAN","DANIEL","DARREN","DAVID","DECLAN","DENIS","DERMOT","DONAL","EDWARD","EOIN","ERIC","FERGAL","FINN","FRANCIS","GARETH","GARRY","GAVIN","GEORGE","GERARD","GERRY","GRAHAM","HARRY","HUGH","IAN","JACK","JAMES","JASON","JOE","JOHN","JONATHAN","JOSEPH","KEITH","KEVIN","KIERAN","LEON","LIAM","LUKE","MARK","MARTIN","MATTHEW","MICHAEL","NEIL","NOEL","OWEN","PATRICK","PAUL","PETER","PHILIP","RAYMOND","RICHARD","ROBERT","RONAN","RORY","SAM","SEAMUS","SEAN","SHANE","SIMON","STEPHEN","TERENCE","THOMAS","TONY","VINCENT","WILLIAM",
  "AISLING","AMANDA","AMY","ANNA","ANNE","AOIFE","BRIDGET","CAROL","CAROLINE","CATHERINE","CIARA","CLAIRE","DEIRDRE","EDEL","ELAINE","ELIZABETH","EMMA","ERIN","EVA","FIONA","FRANCES","GEMMA","GRACE","HANNAH","HELEN","JANE","JENNIFER","JOAN","JOANNE","JULIE","KAREN","KATE","KATHLEEN","KATIE","LAURA","LISA","LOUISE","MAIREAD","MARGARET","MARIE","MARY","MEGAN","MICHELLE","NAOMI","NIAMH","NORAH","OLIVIA","PATRICIA","PAULA","RACHEL","REBECCA","ROISIN","SARAH","SHANNON","SINEAD","SIOBHAN","SOPHIE","SUSAN","TERESA","TRACY"
];

// Completely fictional street/town/county names for screen safety.
const STREET_POOL = [
  "HAWTHORN VIEW","FOXGLOVE AVENUE","BLACKTHORN PARK","ASHBROOK DRIVE","RIVERSTONE CLOSE","ELMWOOD GREEN","WILLOWBANK ROAD","SILVER OAK RISE","LAUREL HILL","BIRCHFIELD AVENUE","MAPLE COURT","THE WILLOWS","OAKRIDGE PARK","ROWAN MEADOW","FERNDALE GROVE","CEDAR VIEW","HAZELWOOD CLOSE","THE COPSE","HEATHERFIELD","KINGFISHER PARK","STONEBROOK WAY","MILLBROOK VIEW","BROOKFIELD AVENUE","RIVERGLEN","MEADOWBROOK PARK","PARKLANDS","THE HAWTHORNS","GLENWOOD RISE","LAKESIDE GREEN","HILLVIEW COURT","THE PADDOCKS","SPRINGFIELD AVENUE","WOODLAND CLOSE","PINE RIDGE","CHESTNUT PARK","SYCAMORE COURT","THE ORCHARDS","MEADOWVIEW","LARKSPUR DRIVE","CLOVERFIELD","WHITETHORN GROVE","FOXBURROW","RAVENSWOOD","THE COPPICE","BEECHWOOD RISE","SANDSTONE PARK","GLENBROOK","RIVERFIELD","MEADOWRIDGE","HOLLYBROOK","THE BRIARS","LAURELBROOK","ELMWOOD HEIGHTS","STONEHAVEN","WOODHAVEN","RIVERBEND","WATERMILL CLOSE","ASHFIELD","OAKFIELD","THE GLADE"
];

const TOWN_POOL = [
  "ARDGLEN","RIVERFORD","BALLYMORE","FOXDALE","KILBRIDGE","DUNHAVEN","ASHBOURNE CROSS","GLENROSS","STONEFIELD","OAKVALE","LOUGHMORE","MILLFORD","RATHGLEN","KILMOUNT","GREENHAVEN","WESTBROOK","BLACKRIDGE","EASTHAVEN","GLENMERE","HIGHCROSS","BRACKENVALE","RAVENMOUNT","CARRIGDALE","SILVERFORD","ASHMERE"
];

const COUNTY_POOL = [
   "ANTRIM",
  "ARMAGH",
  "CARLOW",
  "CAVAN",
  "CLARE",
  "CORK",
  "DERRY",
  "DONEGAL",
  "DOWN",
  "DUBLIN",
  "FERMANAGH",
  "GALWAY",
  "KERRY",
  "KILDARE",
  "KILKENNY",
  "LAOIS",
  "LEITRIM",
  "LIMERICK",
  "LONGFORD",
  "LOUTH",
  "MAYO",
  "MEATH",
  "MONAGHAN",
  "OFFALY",
  "ROSCOMMON",
  "SLIGO",
  "TIPPERARY",
  "TYRONE",
  "WATERFORD",
  "WESTMEATH",
  "WEXFORD",
  "WICKLOW"
];

const PEOPLE = [];
